services:
  secretary-services:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
      - ./temp-processing:/app/temp-processing
      - ./cache:/app/cache
      - ./config/config.yaml:/app/config/config.yaml
    depends_on:
      - mongodb
    environment:
      - OPENAI_API_KEY=sk-proj--
      - MONGODB_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 